# Generated by Django 5.1.15 on 2026-06-30 23:13

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, unique=True, verbose_name='شماره سفارش')),
                ('token', models.CharField(default=apps.orders.models._gen_token, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت\u200cشده'), ('PACKED', 'بسته\u200cبندی'), ('SHIPPED', 'ارسال\u200cشده'), ('DELIVERED', 'تحویل\u200cشده'), ('CANCELED', 'لغو\u200cشده')], default='PENDING', max_length=16, verbose_name='وضعیت')),
                ('receiver_name', models.CharField(max_length=120, verbose_name='نام گیرنده')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('province', models.CharField(choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=40, verbose_name='استان')),
                ('city', models.CharField(max_length=60, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('address_line', models.TextField(verbose_name='آدرس کامل')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات سفارش')),
                ('shipping_method', models.CharField(blank=True, max_length=32, verbose_name='روش ارسال')),
                ('shipping_label', models.CharField(blank=True, max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='جمع اقلام')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='تخفیف')),
                ('vat_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مالیات')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه ارسال')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ کل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(blank=True, max_length=100)),
                ('unit_label', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
    ]
