# Generated by Django 5.1.15 on 2026-07-13 12:25
#
# Order item quantities become whole numbers. Any legacy fractional snapshot
# (e.g. «۰٫۵ کیلوگرم» from the per-kilogram era) is rounded UP to 1 before the
# type change; line_total keeps the original (correct) charged amount.

import math

from django.db import migrations, models


def _integerize_quantities(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    for item in OrderItem.objects.all():
        item.quantity = max(1, math.ceil(item.quantity))
        item.save(update_fields=["quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_integerize_quantities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
