# Generated by Django 5.1.15 on 2026-06-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='کد')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'درصدی'), ('FIXED', 'مبلغ ثابت (تومان)')], default='PERCENT', max_length=10, verbose_name='نوع')),
                ('value', models.DecimalField(decimal_places=0, help_text='درصدی: ۰ تا ۱۰۰ — مبلغ ثابت: تومان', max_digits=12, verbose_name='مقدار')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, help_text='فقط برای نوع درصدی', max_digits=12, null=True, verbose_name='سقف تخفیف (تومان)')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='حداقل مبلغ سفارش')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='از تاریخ')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف دفعات استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='دفعات استفاده\u200cشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='orders.order')),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کد تخفیف',
            },
        ),
    ]
