# Generated by Django 5.1.15 on 2026-06-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=32, verbose_name='درگاه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ (تومان)')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='کد مرجع')),
                ('ref_id', models.CharField(blank=True, max_length=128, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PAID', 'موفق'), ('FAILED', 'ناموفق')], default='PENDING', max_length=16, verbose_name='وضعیت')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ خام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
