# Generated by Django 5.1.15 on 2026-07-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='هش شماره کارت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='شماره کارت (ماسک\u200cشده)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='پیام درگاه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت درگاه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='شناسه تراکنش (trackId)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='شماره پیگیری / مرجع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
