# Generated by Django 5.1.15 on 2026-06-30 22:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('origin', models.CharField(blank=True, help_text='مثل «کرمان»', max_length=100, verbose_name='خاستگاه')),
                ('sale_unit', models.CharField(choices=[('WEIGHT', 'وزنی (کیلوگرم)'), ('PIECE', 'واحدی (قوطی/عدد)')], default='WEIGHT', max_length=10, verbose_name='واحد فروش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتخب صفحه اصلی')),
                ('is_fresh', models.BooleanField(default=False, help_text='نمایش نشان «تازه پخت»', verbose_name='تازه پخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='کد کالا (SKU)')),
                ('label', models.CharField(blank=True, help_text='مثل «قوطی ۲۰۰ گرمی»', max_length=100, verbose_name='برچسب')),
                ('weight_grams', models.PositiveIntegerField(blank=True, help_text='فقط برای واحدی — وزن هر عدد', null=True, verbose_name='وزن (گرم)')),
                ('unit_price', models.DecimalField(decimal_places=0, help_text='وزنی: قیمت هر کیلوگرم — واحدی: قیمت هر عدد', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت واحد (تومان)')),
                ('is_weighted', models.BooleanField(default=False, verbose_name='وزنی')),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='حداقل سفارش')),
                ('qty_step', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='گام سفارش')),
                ('stock_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصول',
                'ordering': ['unit_price'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='catalog_pro_is_acti_e6e001_idx'),
        ),
    ]
