# Generated by Django 5.1.15 on 2026-07-13 12:25
#
# Quantities become whole numbers of fixed packages. Legacy fractional values
# (e.g. min_order_qty 0.5 kg from the per-kilogram era) are normalized to
# integers BEFORE the column type changes, so the conversion is deterministic
# on every backend instead of relying on DB cast/rounding behavior.

import math

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def _integerize_quantities(apps, schema_editor):
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    for variant in ProductVariant.objects.all():
        variant.min_order_qty = max(1, math.ceil(variant.min_order_qty))
        variant.stock_qty = math.floor(variant.stock_qty)
        variant.save(update_fields=["min_order_qty", "stock_qty"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_integerize_quantities, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_weighted',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='qty_step',
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_unit',
            field=models.CharField(choices=[('WEIGHT', 'جعبه\u200cای (وزن ثابت)'), ('PIECE', 'ظرفی (عددی)')], default='WEIGHT', max_length=10, verbose_name='واحد فروش'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='label',
            field=models.CharField(blank=True, help_text='مثل «جعبه نیم کیلویی»', max_length=100, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداقل سفارش'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت هر بسته (جعبه یا ظرف)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='وزن ثابت هر بسته/ظرف', null=True, verbose_name='وزن (گرم)'),
        ),
    ]
