# Generated by Django 5.1.15 on 2026-07-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productvariant_is_weighted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, help_text='ویژگی فرعی که ریزتر زیر نام می\u200cآید، مثل «روغن حیوانی»', max_length=100, verbose_name='زیرعنوان'),
        ),
    ]
