# Generated by Django 5.1.15 on 2026-07-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='اگر تصویر مخصوص یک جعبه/ظرف است، آن را انتخاب کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.productvariant', verbose_name='نوع محصول'),
        ),
    ]
